version: '3.4'

services:
  pulsardeadlettertest:
    image: ${DOCKER_REGISTRY-}pulsardeadlettertest
    build:
      context: .
      dockerfile: PulsarDeadLetterTest/Dockerfile
  
  pulsar:
    image: apachepulsar/pulsar    
    environment:
      - BOOKIE_MEM=" -Xms512m -Xmx512m -XX:MaxDirectMemorySize=1g"
    command: >
      /bin/bash -c
      "bin/apply-config-from-env.py conf/standalone.conf
      && bin/pulsar standalone"
    ports:      
      - "6650:6650"
      - "8080:8080"